# Generated by Django 4.2.27 on 2026-01-23 02:10

import apps.projects.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='temp', max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('add1', models.CharField(max_length=100)),
                ('add2', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(max_length=10)),
                ('city', models.CharField(blank=True, max_length=125, null=True)),
                ('tel', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50)),
                ('start_date', models.DateField(auto_now=True)),
                ('rooms_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='{photo_path}/signature')),
                ('project', models.ForeignKey(default='eg', on_delete=django.db.models.deletion.CASCADE, related_name='sign', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
                ('room_size', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.projects.models.photo_path)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('project', models.ForeignKey(default='eg', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='projects.project')),
            ],
        ),
    ]
