# Generated by Django 4.2.27 on 2026-01-28 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_room_room_size_project_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='room',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign', to='projects.project'),
        ),
    ]
