# Generated by Django 2.1.5 on 2020-03-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
                ('room_size', models.CharField(max_length=50)),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='media/room/pics/')),
            ],
        ),
    ]
