# Generated by Django 2.1.5 on 2020-03-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='room/pics/'),
        ),
    ]
