# Generated by Django 2.1.5 on 2020-03-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200305_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='photo_path'),
        ),
    ]
