# Generated by Django 2.1.5 on 2020-03-06 00:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200305_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.photo_path),
        ),
    ]
