# Generated by Django 2.1.5 on 2020-03-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200306_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='pic1',
            new_name='img',
        ),
    ]
