# Generated by Django 2.1.5 on 2020-03-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='my_Add/signature'),
        ),
    ]
