# Generated by Django 2.1.5 on 2020-03-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200308_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50)),
                ('add1', models.CharField(max_length=100)),
                ('add2', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
