# Generated by Django 2.1.5 on 2020-03-15 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200314_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='project',
            field=models.ForeignKey(default='eg', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.Project'),
        ),
    ]
